
# Русские имена столбцов
COLUMNS_RUS = {
    'complectation': 'Комплектация',
    'condition': 'Состояние/пробег',
    'dealer': 'Имя дилера',
    'for_order': 'Под заказ',
    'in_stock': 'Наличие',
    'link': 'Ссылка',
    'mark_model': 'Марка, модель',
    'max_price': 'Макс. цена',
    'max_price_difference': 'Разница макс. цена',
    'min_price_no_discount': 'Мин. цена без скидок',
    'min_price_no_discount_difference': 'Разница мин. цена без скидок',
    'min_price_with_discount': 'Мин. цена со скидками',
    'min_price_with_discount_difference': 'Разница мин. цена со скидками',
    'modification': 'Модификация',
    'photos': 'Количество фото',
    'position_actual': 'Позиция по актуальности',
    'position_price': 'Позиция по цене',
    'position_total': 'Позиция общая',
    'price_no_discount': 'Цена без скидок',
    'price_no_discount_difference': 'Разница цены без скидок',
    'price_with_discount': 'Цена со скидками',
    'price_with_discount_difference': 'Разница цены со скидками',
    'region': 'Регион',
    'services': 'Услуги',
    'stock': 'В наличии',
    'tags': 'Стикеры',
    'with_nds': 'Цена с НДС',
    'year': 'Год',
}
